---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-cronjob-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-cronjob-deploy
  template:
    metadata:
      labels:
        app: simple-cronjob-deploy
    spec:
      containers:
        - name: pi
          image: perl
          command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(1000)"]
          ports:
            - containerPort: 9876

# It crashes and ends up in crashbackloop since the restartPolicy is by
# default always. Cannot set to never since its a deployment kind
