---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-agent
  namespace: default
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mysql-agent
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mysql-agent
subjects:
  - kind: ServiceAccount
    name: mysql-agent
    namespace: default
---
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: my-app-db
spec:
  secretName: mypwds
  tlsUseSelfSigned: true
  instances: 1
  # router:
  #   instances: 1
# apiVersion: mysql.oracle.com/v1
# kind: Cluster
# metadata:
#   name: my-app-db
#   namespace: default
# spec:
#   instances: 1
