---
apiVersion: v1
kind: Namespace
metadata:
  name: application
  labels:
    name: user_a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nginx
  namespace: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-nginx 
  template:
    metadata:
      labels:
        app: simple-nginx 
    spec:
      containers:
        - name: nginx-pod
          image: nginx:stable-alpine3.17-slim
          ports:
            - containerPort: 9875
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: application
  name: user_a
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
