apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-read-bind
  namespace: application
subjects:
  # We dfine a user which plays a role, abide by the role rules
- kind: User
  name: user-reader
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: user-read
  apiGroup: rbac.authorization.k8s.io
